### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by bb2sol** [bb2sol/RoyalstyleSimulator#1]
기본 기능
- 아이템창에서 로얄스타일 아이템 더블클릭 > 빅헤드 대화창 출력
- 이미지 위컴알에서 가져오기
- 누적 사용 캐시 출력
- 로얄 까면 인벤토리에 아이템 갯수 변동

추가 기능
- 아이템 hover시 아이템 정보 layer 노출
- 키보드 조작 구현
- 로얄스타일 외 원더베리 등 시뮬레이터 개발

**Comment by bb2sol** [comment]
기본기능 08/09

**Comment by bb2sol** [comment]
https://maplestory.wiki/KMS/389/item/5680257

**Comment by bb2sol** [comment]
먼저 할 거
- [x] 뽑은 아이템 이미지 구현
- [ ] 파일 정리
- [ ] 아이템창 구현 (로얄스타일만)
- [ ] 효율적으로 코드 바꿔보기
- [ ] GULP 세팅
- [ ] 이미지 스프라이트 관리 - sprithsmith

나중에 할 거
- [ ] 아이템창 구현 (뽑은 아이템 확인하는거)
- [ ] 랜덤 함수 개선
- [ ] 로얄 기수 업데이트

**Comment by bb2sol** [comment]
dpi 달라도 폰트 동일하게 노출되도록 처리 (확인필요)
@media (-webkit-min-device-pixel-ratio: 2),
       (min-resolution: 192dpi) {
